version: '3.9'

services:
  api:
    build:
      context: .
    container_name: logreport-api
    ports:
      - "8000:8000"
    command: uvicorn app.run:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app